---
version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
      - david-tomson

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
      - david-tomson

  - package-ecosystem: "npm"
    directory: "/packages/botway.js"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
      - david-tomson

  - package-ecosystem: "pip"
    directory: "/packages/botway.py"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
      - david-tomson

  - package-ecosystem: "cargo"
    directory: "/packages/botway-rs"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
      - david-tomson

  - package-ecosystem: "cargo"
    directory: "/installer"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx

  - package-ecosystem: "bundler"
    directory: "/packages/bwrb"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx

  - package-ecosystem: "nuget"
    directory: "/packages/botnet"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
      - david-tomson

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx

  - package-ecosystem: "docker"
    directory: "/dockerfiles"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx

  - package-ecosystem: "docker"
    directory: "/.gitpod"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
